# Branch Protection Configuration
# This file documents the recommended branch protection settings for this repository
# These settings should be applied manually in GitHub Settings > Branches

main:
  protection:
    required_status_checks:
      strict: true
      contexts:
        - "CI Pipeline (test)"
        - "Security (security)"
        - "CodeQL"
    enforce_admins: true
    required_pull_request_reviews:
      required_approving_review_count: 2
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      restrict_pushes: true
    restrictions:
      users: []
      teams: []
    required_linear_history: true
    allow_force_pushes: false
    allow_deletions: false

develop:
  protection:
    required_status_checks:
      strict: true
      contexts:
        - "CI Pipeline (test)"
        - "Security (security)"
    enforce_admins: false
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
    restrictions:
      users: []
      teams: []
    required_linear_history: false
    allow_force_pushes: false
    allow_deletions: false